version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
volumes:
  data:
